// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRRSSvpcOwgte5rRsfPeQxOHiQErWzuoQ',
    appId: '1:182669456051:web:c3268c86fa0a1318a2f6c6',
    messagingSenderId: '182669456051',
    projectId: 'gpotter-b5384',
    authDomain: 'gpotter-b5384.firebaseapp.com',
    storageBucket: 'gpotter-b5384.appspot.com',
    measurementId: 'G-TTSVEVYFMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfA28vEB2RBhIeoLFUTKLoH2X9tjRyh2E',
    appId: '1:182669456051:android:1dc7680cbb0cca75a2f6c6',
    messagingSenderId: '182669456051',
    projectId: 'gpotter-b5384',
    storageBucket: 'gpotter-b5384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYe9cQPm_21dxVhz59Qohe-un7htiAr0',
    appId: '1:182669456051:ios:c32bbb628863c306a2f6c6',
    messagingSenderId: '182669456051',
    projectId: 'gpotter-b5384',
    storageBucket: 'gpotter-b5384.appspot.com',
    iosClientId: '182669456051-mck8af5pdrljue6m0mqf8pe0gm1o3lub.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGpotter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnYe9cQPm_21dxVhz59Qohe-un7htiAr0',
    appId: '1:182669456051:ios:c32bbb628863c306a2f6c6',
    messagingSenderId: '182669456051',
    projectId: 'gpotter-b5384',
    storageBucket: 'gpotter-b5384.appspot.com',
    iosClientId: '182669456051-mck8af5pdrljue6m0mqf8pe0gm1o3lub.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGpotter',
  );
}
